### ISSUE TITLE
Move giving.cu.edu/picture-this to essential.cu.edu/impact-reports/picture-this

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#104]
https://github.com/CUCentralAdvancement/essential-cu/issues/102 basically just worked. We still need to figure out what to do with individual package.json and gulp files when sub-projects are combined with a larger project and the root project controls the build process, but this could be an a quick win to get more pages off of Pantheon.

The documentation about routes define in public/ files is a little thin in https://nextjs.org/docs/basic-features/static-file-serving. Beyond describing that conflicting paths will result in an error vs. using a hierarchy of index.php then static or static then index.php with mod_redirect that we are used to with a PHP host like Pantheon, it isn't really clear if there is any performance hit from loading up public/ with all these bloated css/js/asset dirs.

**Comment by kreynen** [comment]
This project has a number of full resolution images in stories-photos like arts-ryan-hero-1.jpg (21MB). The same file is also available as arts-ryan-hero-1.jpeg (350k). 

Need to confirm only the resized images are using the HTML/CSS/JS and remove those.

**Comment by kreynen** [comment]
https://github.com/CUCentralAdvancement/cu-giving/blob/1227335a0abcc779e3869f7b9463a861d834754f/picture-this/style.css#L7470 makes me slightly ill.

home-students.png (4MB), home-societal.png (3.6MB) home-innovation.png (2.5MB), etc weren't actually used. Those unnecessarily large files were just slowing down ever clone and backup for 2 years for no reason. Deleted and fixed what was obvious in https://github.com/CUCentralAdvancement/essential-cu/commit/8e7cb9117ab9b556f36be52174bbb1eb7f8a4f54

**Comment by kreynen** [comment]
There are a lot of things that could be improved in https://essential-cu-feature-10-6traeu.herokuapp.com/impact-reports/picture-this/index.html including https://github.com/CUCentralAdvancement/cu-giving/issues/49, but like https://github.com/CUCentralAdvancement/essential-cu/issues/102 the Heroku version is already an improvement.

**Comment by alexfinnarn** [comment]
Keep in mind Cloudinary can be used to add to compression techniques, and I guess they do a lot by default: https://cloudinary.com/documentation/image_optimization#default_optimizations. I think, with auto-upload + now controlling all Cloudinary code, that it might be seamless to point images on Pantheon to auto-upload on Cloudinary.

This makes migrating content easier since images embedded in code can be simply be replaced with the Cloudinary bucket name URL. Switching schemes from `public://` to `cloudinary://` might even do that automatically...

I will attempt to do some of the work in https://github.com/CUCentralAdvancement/digital-dash-cu-adv/issues/174

**Comment by kreynen** [comment]
@alexfinnarn I didn't know about https://docs.fastly.com/en/guides/about-fastly-image-optimizer until I came across it for this project, but that also gives us some options.

**Comment by tskillern** [comment]
@kreynen looks good to me. Couldn't find any issues.
