### ISSUE TITLE
CMS won't wrap IMG in P tag; strips out P tags when manually insert

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#115]
@alexfinnarn 

Kelly noticed that some in-body images were not wrapped in a P tag and thus weren't rendering correctly. (They were not as wide as they should be, nor were the captions displaying.) I noticed this, too, but he found a fix on the front end before I could create this issue for you. 

Take a look at this screen capture here: https://www.dropbox.com/s/6iqycuwf14eho00/paragraph%20tags.mov?dl=0

Steps to replicate: 

1. Place an image in the body using the picture-tool insert icon 

2. Verify in source view that the IMG tag is not contained within a P tag

3. Add P tags around the image

4. Toggle back to WYSIWYG view and then back to source view 

5. Verify that P tags are stripped out (note that P tags are NOT stripped out in Chrome but are in Firefox)

What I cannot account for is that there are IMG tags that are contained within P tags throughout all the stories. These are ones that Melanie placed in the stories. I do not know what browser she used. But even if she's using Chrome, I do not think that Melanie went back into the code to add P tags.

**Comment by alexfinnarn** [comment]
Well, first of all, the image tags should probably not be in paragraphs as I imagine paragraphs have styling attached to them that doesn't have anything to do with an image. I didn't check the HTML specifically since my job was to make sure text, images, and I guess blockquotes could go into that field, and we had some trouble with simply uploading and keeping references to images up to this point.

I left the defaults of the WYSIWYG/CKEditor as they were, and there are filters to "correct HTML" and "insert paragraph tags for line breaks". So, that's why the images are in `<p></p>` tags: they're on separate lines. That all makes sense and filters could be changed to remove this or that or add the `<div class="story-image-container"><div class="container">...` around images...or some other solution.

But at this point, it's better and faster to do things manually than write code to parse and handle logic. I'm not sure why different browsers would have different behavior, but I know figuring that out would take more time than trying to guess and code up a solution.

<img width="361" alt="Screen Shot 2020-10-15 at 12 20 24 PM" src="https://user-images.githubusercontent.com/3640707/96165066-1e64f100-0eea-11eb-828c-15e2e132523a.png">

The bottom left-hand corner of the WYSIWYG can show you the "markup tree" of the current element you're editing. At one point, I did see "body image" when normally I would see "body p image" but I couldn't get that to happen again. 

I use the Brave browser and it is more obscure than Chrome or Firefox and has its own host of issues that don't appear when I use Chrome. Even a single browser extension can insert markup into a WYSIWYG field that looks hidden to the user until someone sees the source. Or even the form won't save because of the extension and that is harder to debug...but this did happen. So, most every dev hates WYSIWYG editors due to the fact you never get exactly what you might see on the frontend.

<img width="262" alt="Screen Shot 2020-10-15 at 12 32 28 PM" src="https://user-images.githubusercontent.com/3640707/96165630-e1e5c500-0eea-11eb-8b2d-457aee26722e.png">

I added a "Full HTML" text format that you can switch to from the WYSIWYG format and that won't apply any filters so the markup will remain the same there. I also took off a filter on the WYSIWYG editor that corrects faulty HTML and strips out extraneous markup. You can attempt to switch back and forth between text formats and it will most likely work, but you do get a warning each time you try. The stories are revisioned though and can be reverted through the "Revisions" tab on story edit screens if need be.

In conclusion, you can now switch to source in WYSIWYG mode on a story, add the needed markup, and then switch it back to the WYSIWYG output. Or you can switch to Full HTML, edit the markup, and leave it in that mode so you're sure whoever edits the page knows what they're saving and no cross-browser issues come into play.

On http://digital-dash-adv-cu.herokuapp.com/node/6/edit I added the parsing logic's additional HTML of https://github.com/CUCentralAdvancement/essential-cu/blob/master/pages/impact-reports/onward/%5Bslug%5D.js#L27 and it saves correctly as you can see in the output of https://essential-staging-cu.herokuapp.com/impact-reports/onward/korey-wise-colorado-law-school.

So, at this point you can add the markup Kelly is using code to parse or keep the images in paragraph tags and make sure the HTML is saved like that. I can also make sure the output is correct before reviewing PRs and correct it if not, but writing more code makes no sense with the number of stories and time left till launch.

cc @mattroush

**Comment by tskillern** [comment]
Thanks for the explanation. I'll close this since we have a solution so close to launch. I was more providing this issue in case you wanted to see the behavior of the editor for applications/clarity beyond this project.
