### ISSUE TITLE
Update giving.cu.edu banner with IR20 banner 

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#135]
@alexfinnarn please update the giving.cu.edu banner to this :
https://www.dropbox.com/s/zza4m3ili8lcep5/IR20-giving%20site-webbanner.jpg?dl=0

**Comment by alexfinnarn** [comment]
will do...and just FYI to others we are tracking this way because it's easier for access control. This issue will move to the cu-giving repo after it has been reviewed, so the history can be stored in that project. In the future, I think there might be a "triage GH project" with templates for submitting dev issues and then some automation would help to keep GH repos active where development is but allow communication with the submitter so that we don't have to add and remove a bunch of people per project...and then have them remember where to post issues...only one place to go, use and follow.

**Comment by alexfinnarn** [comment]
Updated on https://giving-test.cu.edu/university-colorado 

@tskillern and @mattroush not sure when this is supposed to "go live" but it can be approved on Pantheon staging.

**Comment by duquennoisa** [comment]
@alexfinnarn sorry I made an update to the image and thought I had replaced it in dropbox but it just copied it, 

here is the image https://www.dropbox.com/s/ztljyp56bh5wqeg/IR20-giving%20site-webbanner.jpg?dl=0

**Comment by alexfinnarn** [comment]
Banner updated on https://giving-test.cu.edu/ but the link text and URL are not yet changed. What should those be?

**Comment by tskillern** [comment]
@alexfinnarn 

Banner text: Learn how your gifts make a difference at CU

URL: https://essential.cu.edu/impact-reports/onward/?utm_campaign=2020ImpactReport&utm_source=GivingWeb

**Comment by alexfinnarn** [comment]
@tskillern block updated with changes at https://giving-test.cu.edu/

**Comment by alexfinnarn** [comment]
I also made this change on https://giving.cu.edu/ ...let me know if needs changed by re-opening this issue.
