### ISSUE TITLE
Complete AR19 deployment

### ISSUE THREAD

**Issue by mattroush** [CUCentralAdvancement/essential-cu#165]
- [ ] Redirect giving.cu.edu/annual-report/2019 to essential.cu.edu
- [ ] Update other giving.cu.edu redirects to point to new URLs
- [x] Remove code from the cu-giving repo

**Comment by mattroush** [comment]
@tomchekj Please work with @imkleats to identify the new URLs for these 2019 annual report vanity URLs and update them in D7 to point to the new URL. Redirects are found here: https://giving.cu.edu/admin/redirect-analysis?combine_op=contains&combine=annual-report

**Comment by imkleats** [comment]
**Story (Resilience)**
- Old Link: https://giving.cu.edu/annual-reports/2019/story.php?5pHvMTYkI6qAtRlsGxsVqV
- New Link: http://essential.cu.edu/impact-reports/together/story/resilience

**Story (Community)**
- Old Link: https://giving.cu.edu/annual-reports/2019/story.php?id=1a9AAkTCKQ9V3n6Urcsaq0
- New Link: http://essential.cu.edu/impact-reports/together/story/community

**Story (Innovation)**
- Old Link: https://giving.cu.edu/annual-reports/2019/story.php?id=3shO3Vyy5NA2hhazVVNLrx
- New Link: http://essential.cu.edu/impact-reports/together/story/innovation

**Story (Wonder)**
- Old Link: https://giving.cu.edu/annual-reports/2019/story.php?id=6vDZM13EkpuzvZKcSpW0Gh
- New Link: http://essential.cu.edu/impact-reports/together/story/wonder

**Comment by tomchekj** [comment]
I updated all of the redirects. Would someone be able to just double check to make sure that everything looks all good when you have a chance? No rush. Thanks guys!

**Comment by alexfinnarn** [comment]
@imkleats @tomchekj I created a multi-dev instance with AR19 plus a bunch of other old files removed: https://remove-ar19-cu-giving.pantheonsite.io/

I pulled the database from production; however, I don't see the redirects mentioned above for any "annual-reports" links. I did add https://remove-ar19-cu-giving.pantheonsite.io/annual-reports/2019 to the multi-dev site and that should redirect for you. If you let me know when the redirects are all in place, I can pull back the prod db and check again. 

One thing that could have tripped people up is caching. I had to clear the cache to get my redirect to show up...so, I'm not sure if this would also work with the files there and if we thought it was broken due to menu router caching.

**Comment by alexfinnarn** [comment]
https://remove-ar19-cu-giving.pantheonsite.io/annual-reports/2019/story.php?id=6vDZM13EkpuzvZKcSpW0Gh kind of works but essential-cu needs to know which query params to remove...if that matters.

**Comment by alexfinnarn** [comment]
I will push this up to production and run the regular deployment tests as well as adding a couple of tests for these redirects.

**Comment by alexfinnarn** [comment]
I'm trying to fix the Cypress tests, and I did add new tests for the redirects listed above. I would have deployed this today without fixing testing, but now I will deploy it tomorrow morning...wait, that violates the "no deploys on Fridays" rule so I will wait till...Tuesday, I guess. This isn't critical so that should be fine.

**Comment by alexfinnarn** [comment]
Deployed on 06/01/2021. I had to rearrange some Cypress tests but they all pass now...and should reliably do so going forward. 

The only issue was a form element getting skipped over and Cypress saying the element didn't exist once it was out of view.  I'm not sure if an option to the assertion can help, but it was easy to rearrange the test to match the order of elements in the actual form.
