### ISSUE TITLE
Add credits collapsable item to footer

### ISSUE THREAD

**Issue by duquennoisa** [CUCentralAdvancement/essential-cu#469]
I created a design for the credits section
I updated it on the desktop homepage board on invision and moved the components up in the prototype. 

Here it is on the Homepage: https://invis.io/YG11WIQKEVXT
Desktop version closed: https://invis.io/TX11YA4C9SGK
Desktop version open: https://invis.io/AS11YA49KMW2

I can make a mobile version if needed. Let me know. 
The text will be verified but is likely to be very close to this. I'll update the issue with any text changes. 

**Acceptance Criteria**

- [ ] Added credits menu for desktop and mobile to footer section.

**Comment by duquennoisa** [comment]
I'm checking with Tim on the priority level for this. Will circle back.

**Comment by alexfinnarn** [comment]
@duquennoisa I added the footer credits. Some notes:

- The shadow is probably not what you want, but it is using `shadow-md` which is `box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)`. I don't mess around with box shadows much at all, but I can insert whatever you'd like there...I made a note about box shadows, in general, in #347.
- The font sizes are slightly larger than InVision reports but it looks visually similar to mocks based on the font sizes used already. They can be adjusted up or down but should stay in the scale used elsewhere.
- The border-radius is set to `45px` which is used elsewhere but you might want it larger or smaller.
- Since there was no mobile version, I just left it as-is, but the smaller the screen, the line breaks, and centered text might not be what you want.

**Comment by duquennoisa** [comment]
Here are some shadow values for the credits div
--tw-shadow: 0 -6px 5px -1px rgba(0, 0, 0, 0.5), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);

![image](https://user-images.githubusercontent.com/70037329/140384539-31c0c852-b4e3-4740-a8c6-bb90c6e3b32d.png)

To create the layered look with the footer can you add this styling:
z-index: 10;
    --tw-shadow: 0 -3px 5px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);

![image](https://user-images.githubusercontent.com/70037329/140384430-5b236207-5138-4914-8c53-0eec8193f97b.png)


While you're at it can we create the layered look with the header too by adding these changes to the header:
    --tw-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
}

![image](https://user-images.githubusercontent.com/70037329/140382357-03a379f9-4821-46e5-b924-9d025c64062b.png)

And this change the white div:
z-index: 10;
    --tw-shadow: 0 2px 6px -1px rgba(0, 0, 0, 0.3), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    box-shadow: var(--tw-ring-offset-shadow, 0 0 #0000), var(--tw-ring-shadow, 0 0 #0000), var(--tw-shadow);
    
    
![image](https://user-images.githubusercontent.com/70037329/140383500-5b34e9cf-a6b9-4aee-a2c4-2aef69d7a858.png)

**Comment by alexfinnarn** [comment]
@duquennoisa I added the shadows and they definitely look different than before. The values should be as you requested.

**Comment by duquennoisa** [comment]
@alexfinnarn This looks good in the staging environment! I'll go ahead and close this. 

Will these changes get pushed before 11 MST? (we are presenting to CUF at that time)
