### ISSUE TITLE
(4) There's an extra hard return between the two graphs under the Lampe/husband/beach photo.

### ISSUE THREAD

**Issue by Feissit** [CUCentralAdvancement/essential-cu#480]
Extra line of space between these two grafs: 

![Screen Shot 2021-11-02 at 1 28 42 PM](https://user-images.githubusercontent.com/91230278/139936916-f0812879-4e69-40cd-aaf9-14bef8dea7a1.png)

**Comment by alexfinnarn** [comment]
<img width="1032" alt="Screen Shot 2021-11-02 at 8 37 45 PM" src="https://user-images.githubusercontent.com/3640707/139999095-afe7adb6-0dd5-4139-afeb-a2c345236d1a.png">

That's due to the paragraphs being in separate text blocks, and can be fixed by combining them into one text block. Padding is applied to paragraphs within the text block so it adds up to double with two text blocks back to back.
