### ISSUE TITLE
Follow up on IR and using a tool like Webflow

### ISSUE THREAD

**Issue by alexfinnarn** [CUCentralAdvancement/essential-cu#552]
https://webflow.com/ is a great tool that I often hear people using to make simple marketing sites like essential.cu.edu but not have to worry about the dev side of things.

The biggest pain point in recent years has been the "design to dev" process, especially when the changes are one CSS property, and there are many issues where only one might be suggested.

While it might seem like it is quicker for a developer to handle the task, when you account for review time, pushing updates, design review, etc, the process is not quick at all. 

Contrast that with a tool like Webflow where the content creator and designer can work within the tool that actually deploys the code right off the bat. 

As a developer, I can help with training on parts of a tool, but the UI is very similar to a design tool like Sketch or Photoshop, and you can click to edit items so people don't have to figure out where bits of data come from.

I estimate IR21 cost would cost well over $100K if paying the market rate to a vendor whereas using something like Webflow will end up costing a fraction and free up CU employees to do other tasks.

Acceptance Criteria:

- [x] Try out Webflow via the tutorials and templates
  - [ ] Free templates here - https://webflow.com/templates/free-website-templates
  - [x] Many tutorials here - https://university.webflow.com/
- [x] Set up a meeting to discuss in May with marcomm teams
- [x] Potentially list other tools
  - medium.com is great for writing and can stand alone or serve as a blog in addition to Webflow
  - https://www.systemflow.co/ helps build on top of Webflow similar to Tailwind UI
  - https://www.contentful.com/ can be used as a headless CMS
  - Acquia Site Studio is a bunch of things on top of Drupal and gets towards Webflow with adding styles to components
- [x] Think about the need to write code at all. Is this way of working really needed to produce a good Impact Report?

Next Issue

-  [ ] #564

**Comment by alexfinnarn** [comment]
@ktheiler @tskillern @duquennoisa @Feissit  I'd like to get your thoughts on what I wrote above. I know there is talk of "sunsetting Essential CU", potentially expanding Odder use, and that you are all busy, but for the past two years, the IR has snuck up on me at least and ended up in a situation with the tech stack that was not ideal but had to be used to finish the project. 

I truly think a simple tool like Webflow is a great fit for projects like the Impact Report and the past two years have been way overkill on the tech end at the same time as limiting design and content. There are plenty of other tools to look at, but Webflow is my top recommendation.

Anyhoo, I had this note sitting around so I made it into an issue, and now I have creating this issue off of my todo list. I would have added Sue but she just started and I'm not sure if working with Donor Comms on GitHub will continue, especially if no code is involved in the future.

**Comment by ktheiler** [comment]
Hi @tskillern @duquennoisa @Feissit (and we'll need to get Sue on this thread), @alexfinnarn and I are going to set up time in late April or early May to review the CMS tool(s) for consideration (ie Webflow and possibly Odder - at least want to talk about Odder and it's functionality) so that we can figure out that aspect of the IR project well in advance of starting the nuts and bolts of design and content.

**Comment by tskillern** [comment]
Yes, this works for me. Just so everyone knows (I told Katie separately): There are security review and procurement steps related to something like this. Those can take a while and could affect timelines.

From: ktheiler ***@***.***>
Date: Thursday, April 7, 2022 at 12:18 PM
To: CUCentralAdvancement/essential-cu ***@***.***>
Cc: Tim Skillern ***@***.***>, Mention ***@***.***>
Subject: Re: [CUCentralAdvancement/essential-cu] Follow up on IR and using a tool like Webflow (Issue #552)

Hi @tskillern<https://github.com/tskillern> @duquennoisa<https://github.com/duquennoisa> @Feissit<https://github.com/Feissit> (and we'll need to get Sue on this thread), @alexfinnarn<https://github.com/alexfinnarn> and I are going to set up time in late April or early May to review the CMS tool(s) for consideration (ie Webflow and possibly Odder - at least want to talk about Odder and it's functionality) so that we can figure out that aspect of the IR project well in advance of starting the nuts and bolts of design and content.
