### ISSUE TITLE
Need direction on Story card highlight colors

### ISSUE THREAD

**Issue by kmackvolt** [CUCentralAdvancement/essential-cu#58]
**Home Page requirements** per  _CU IR20 UI-UX requirements 2 for Voltage 3.docx_ :

_4. Some cards will feature a different color based on the interest tag (e.g., blue = student). We’re presuming we can define this in the style guide and it will be handled in the CMS._ 

I don't see any indication of what colors should be used for what conditions other than that note.

I see this list of keywords in helpers.js:
```
const keywords = [
  "buffalo",
  "money",
  "smile",
  "research",
  "university",
  "advancement",
  "buffalos",
  "donation",
  "society",
  "innovation",
  "college",
  "giving",
  "impact",
  "report",
];
```
If these are all "interest" tags, I need to know what color (hex code) to use with each tag you want a color for.
In the mockups it looks like there is both a solid color used on elements like the HR bar, and then a gradient; in case the solid color and the gradient bottom color differ I would need both of course.

I am also assuming since the story cards are used on the Story pages for related stories, that there they should also be displaying those highlight colors, which would enable the same code to be used for story cards in both places.

**Comment by tskillern** [comment]
@duquennoisa  Please see Kelly's request and assign all appropriate colors and variants appropriately to these 3 labels: 

students
research
society

@kmackvolt these are the 3 interest labels we're using. No more.

**Comment by duquennoisa** [comment]
There are 2 hex values tied to the highlighted card.
1.  One is a white -> color gradient for the card space 
2. one is the value replaces the gold lines on the cards :

Students - 1= FFB69F, 2=D94F2A
Research - 1=BCEAE7, 2=065E62
Society- 1=C7BDE3, 2=544181

Highlight = hover on desktop

I know we aren't doing the highlight function for mobile because hover is not an option. If we do end up implementing it for mobile down the line I was imagining it could highlight when the card reaches the vertical center point of the screen.

**Comment by alexfinnarn** [comment]
FYI, https://github.com/CUCentralAdvancement/essential-cu/blob/master/data/types.js#L38 has the three interests + the values for campus tag as well.
