### ISSUE TITLE
Header on mobile needs logo fix and width/resizing fix

### ISSUE THREAD

**Issue by tskillern** [CUCentralAdvancement/essential-cu#60]
@kmackvolt 

Regarding: https://github.com/CUCentralAdvancement/essential-cu/pull/56

I merged because it's in good shape. But we noticed a few mobile bugs that need to be fixed eventually: 

1. In mobile, when tapping hamburger menu: (a) the resulting menu does not expand across the full screen width; it should. (b) the content/images in the main body area change in size. See: ﻿https://www.dropbox.com/s/kioslu348q4kmd2/RPReplay_Final1600278557.MP4?dl=0

2. In mobile, when scrolling down page, the CU logo should disappear. It persists. See: https://www.dropbox.com/s/lv7rhsoht18ouws/Screen%20Shot%202020-09-17%20at%203.34.35%20PM.png?dl=0

**Comment by kmackvolt** [comment]
These fixes will be in the next PR.
1. The page meta viewport tag did not have initial scale specified; I added that. I hadn't noticed it because it only occurs with mobile emulation or on an actual mobile device.
2. I interpreted the direction in the designs which say the mobile logo should be "pinned" as meaning sticky/fixed position. It shouldn't be anything special. Got it.
