### ISSUE TITLE
Story interest tag not available to related story cards on Story pages

### ISSUE THREAD

**Issue by kmackvolt** [CUCentralAdvancement/essential-cu#61]
@alexfinnarn I could use some help with this.
I am working on the story cards for both the index.js and [slug].js pages.

The **interest_tag** is available on the cards on the index.js page, but it is not available to the cards on the [slug].js story pages as used in the related stories section at the bottom of the page. I've tried to follow the logic and the props in helpers.js but I can't get it to come through.

I pushed up my working branch, if you can take a look. Line 136 is where it should be returned; I have a static TESTING string there for now. I deleted all my other "WIP" code except for that.
https://github.com/CUCentralAdvancement/essential-cu/blob/feature/story/data/helpers.js#L136

**Comment by alexfinnarn** [comment]
@kmackvolt This relates to https://github.com/CUCentralAdvancement/essential-cu/issues/38 somewhat, however the name of the terms are in the relationships returned so those names are grabbed in a similar manner. Since the tag/term data is a separate entity, the main story data only contains IDs to the tag entities and the data is included in the separate `relationships` array.

I added a PR you can merge into your branch or take the code from https://github.com/CUCentralAdvancement/essential-cu/pull/63/files I didn't change the `data.types.js` file yet but that is my suggestion on how to get the data.

You'll see that I added a ternary for grabbing the term name since the last `[slug].js` path rendered might be causing the same issue as the "ghost story" comment I wrote about. All the stories should have those tags, but I can investigate if not.

**Comment by kmackvolt** [comment]
@alexfinnarn Thanks for adding that. I merged into master and then my **feature/story** branch.
https://github.com/CUCentralAdvancement/essential-cu/tree/feature/story

**Comment by kmackvolt** [comment]
@alexfinnarn When this issue is fixed I'll the `feature/story` branch ready for PR. 
If it's a lot of effort to fix this, I would suggest we confer with Tim about if having the highlightable interest_tag color functionality for the related stories cards is worth the effort.

**Comment by alexfinnarn** [comment]
@kmackvolt Can you submit the PR of what you have, if the highlight interest_tag color is the only outstanding issue? @tskillern might have comments on other parts of the design outside of that element. Also, if the card highlight is the same look as on the homepage...and those tags come through now...then the styling will look the same here, right?

I will work on the data layer today and I doubt it will be a huge issue to get the data in the same format. However, I won't be able to provide a better answer until after EOD today.

**Comment by kmackvolt** [comment]
PR submitted: https://github.com/CUCentralAdvancement/essential-cu/pull/69

The same story cards do appear on the Home page as do on the related stories section of the Story pages. I have a little temp div visibly displaying the tags in the top left corner of the storycards as well, so you can tell if interest tags are coming through.

**Comment by alexfinnarn** [comment]
should be fixed in #70
