### ISSUE TITLE
Question on "some users" for financials module reorder, and cookies/querystrings in general

### ISSUE THREAD

**Issue by kmackvolt** [CUCentralAdvancement/essential-cu#64]
Requirements V3 doc:
**Home page - Financials content module**
...
_3. For some users (e.g., based on entry into the site), the financials module should be positioned below the title module and above the story cards. Otherwise, it is positioned after the story cards module by default. We will cookie users, so if the user comes back to the page but not through the financials URL, the user should still see this module in this position._ 

Need to identify "some users". Are these users arriving via a querystring link? What's the querystring?

Is anyone else on the CU side working on anything with querystrings or cookies for this project, or do I need to start all this from scratch?

**Comment by kreynen** [comment]
I forwarded you more details as a PDF of our current strategy. Most of that will be implemented via Google Tag Manager, but there will be some overlap like this and https://github.com/CUCentralAdvancement/essential-cu/issues/62

As far as prioritizing the financial information, that will be set in the utm_content value in the emails being sent using Marketing Cloud with a pattern of [campus]_[interest] or just [campus] 

I believe the the way you'd change the order would be if the utm_content value = ucb_financials, ucd_financials, uccs_financials, but I think @tskillern has also talked about setting the utm values to cookies so that if the user come back to the page on the same device the financial would still be prioritized.

Does that make sense? 

I am currently testing the approach we want to use with Marketing Cloud in Drupal 7 on giving.cu.edu. If it's helpful, I can add setting the cookie value based on the utm values to my priorities and you can just base everything on a cookie. 

We'd just need to agree on the name of that cookie/value.

**Comment by tskillern** [comment]
>>> I think @tskillern has also talked about setting the utm values to cookies so that if the user come back to the page on the same device the financial would still be prioritized.

This is correct.

As for what the names of the values are, it doesn’t matter to me (as I mentioned on the call this morning). Please let me know if you need more information from me.

**Comment by kmackvolt** [comment]
> If it's helpful, I can add setting the cookie value based on the utm values to my priorities and you can just base everything on a cookie.

^ @kreynen , If I understand you correctly: You need to deal with UTM value (aka querystring) inputs for your purposes, and can set cookies for that info as well. If that's possible, and thus I only need to deal with reading cookies for my purposes (reordering content), that would be great.
