### ISSUE TITLE
Redirect handling that converts marketing urls into cookies and clean url

### ISSUE THREAD

**Issue by kreynen** [CUCentralAdvancement/essential-cu#76]
Related to https://github.com/CUCentralAdvancement/essential-cu/issues/64

- [x] Consolidate all the marketing/tracking scripts we are using on giving.cu.edu into a single file
- [x] split utm_content values into usable campus and interest cookies
- [ ] redirect users based on querysting for use case like financials PDF
- [ ] configure Fastly VLC to ignore common marketing query string values so this can be cached

We were already planning on using a handful of redirects to add utm values to clean, short urls used in print pieces. We can simplify the values Kelly needs for https://github.com/CUCentralAdvancement/essential-cu/issues/64 by using a "frontdoor" approach for all the "marketed" urls in print, social and Marketing Cloud. Rather than spend time having Kelly figuring out the querystring handling and cookie (for returning visitors) , we can point users we're marketing in social and marketing cloud emails to an end point like https://essential.cu.edu/r?e=kreynen@gmail.com&j=123&utm_interest=ucb_finanicals. We'd push all the utm and mc values back to the respective services as well as add cookies that can be read by both essential.cu.edu and giving.cu.edu. Users would then be redirected to a clean version of the URL so this would also cut down on inadvertently sharing marketing URLs with query string values. This should make Kelly's content customizations easier since he would only use the cookie. This approach has an added bonus of making the urls less complicated by reusing the utm_ values vs. adding more query string values and reducing the chance of someone sharing a URL with tracking data in it.

The r page would simply take a utm_interest=ucb_finanicals, break that up into campus and interest cookies, set the cookies and pass the user off to the IR20 homepage.

**Comment by mattroush** [comment]
@kreynen @kmackvolt Could you two please confirm the details and/or your understanding of the following?

- @kreynen will be responsible for developing the endpoint, cookie creation and redirect functionality.

- @kmackvolt will be responsible for developing front-end to handle dynamic content behavior according to pre-determined cookies and their values.

Please correct if I am wrong here, but despite the use of `utm_interest` in the example above, I believe Kevin and I decided it made more sense to use the standard Google Analytics `utm_content` query param for both GA campaign tracking and to create cookies that will drive IR20 home page dynamic content behavior. Two birds with one stone, if you will.

Values for the `utm_content` query param in the user's link would follow this pattern: `[campusCode]_[interest]`

User's links would send them to an endpoint, as described above, which would capture all applicable query parameters, create the respective cookies and then redirect users to the IR20 home page.

When creating the cookies, the `utm_content` value is parsed into two cookies for handling dynamic content on the IR20 home page: `campus` and `interest`.

The possible values for each and the expected behavior is outlined below.

## "campus" cookie
`campus` cookie will store the short code for each campus, which aligns to the `field_story_campus_tag` value assigned to each story (_that's D9 machine name, not sure if that or a different key is being used in API_). This cookie will determine if and how stories are story cards are sorted on the IR20 home page when user lands on the site.

param/cookie value |  content tag value | behavior
------------------- | ------------------ | ---------
`AMC` | `Anschutz` | Anschutz stories appear first in sort order
`UCB` | `Boulder` | Boulder stories appear first in sort order
`UCD` | `Denver` | Anschutz stories appear first in sort order
`UCCS` | `UCCS` | UCCS stories appear first in sort order
`SYS/CUF` | N/A | This value is used for analytics only. Story cards would appear in default sort order.
`(null)` | N/A | Story cards would appear in default sort order.

## "interest" cookie
`interest` cookie is used to determine whether stories section or financials section should appear first on the IR20 home page. 

**This should not be confused with the "Story Interest Tag" assigned to each story** (`field_story_interest_tag`) -- _this cookie is strictly for determining the order of content sections on the home page_.

param/cookie value |  behavior
------------------- | ----------
`stories` | Stories section with story cards appears above Financials content section
`financials` | Financials content section appears above Stories content section
`(null)` | Content sections appear in default order, Stories above Financials


cc: @tskillern @pspaeth

**Comment by kmackvolt** [comment]
@mattroush Thanks! That makes sense.

**Comment by kreynen** [comment]
We need to scope these cookies to be able to share then better essential.cu.edu and giving.cu.edu, but according to https://stackoverflow.com/questions/1134290/cookies-on-localhost-with-explicit-domain the scoping needs to be removed when running on localhost.

**Comment by kreynen** [comment]
I have a basic version of this that works on both Heroku and yarn dev/localhost now. 

There are few technical issues with the names and values in @mattroush's description. Any cookies that we'd want to be able to access on on giving.cu.edu while it's hosted on Pantheon needs to include a STYXKEY prefix so that the cookie is excluded from the caching. I don't know that we'll need any of these values before we move giving.cu.edu off Pantheon, but I'd rather have access to the cookies then not have access.

So the cookie you care about for personalization is `STYXKEY-Interest`. Campus is `STYXKEY-Campus`.

We also want to avoid a / in a value name whenever possible. If SYS/CUF is always going to be the same, we should just use SYS. If there is some reason to separate those, but have the same behavior, we should use SYS or CUF. If we truly need to combine then, the use SYSCUF or SYSCUF.

**Comment by kreynen** [comment]
I'm still looking at whether the Apache instance running on the dyno can be configured to resolve index.html at the root directory and still working through some cert issues related to https://github.com/CUCentralAdvancement/essential-cu/issues/88, but you can see this working by going to https://essential-cu-feature-76-j9t3v9.herokuapp.com/r/index.html?e=kreynen+test@gmail.com&j=123&utm_content=UCB_financials&utm_media=social and then checking the cookies for the  essential-cu-feature-76-j9t3v9 domain and allowing the cert mismatch.

<img width="848" alt="Screen Shot 2020-10-07 at 9 51 32 AM" src="https://user-images.githubusercontent.com/385234/95357523-305ce900-0885-11eb-8d07-eb26c59cfda1.png">

**Comment by kmackvolt** [comment]
> @kreynen @kmackvolt Could you two please confirm the details and/or your understanding of the following? 
>...
> ## "interest" cookie
> `interest` cookie is used to determine whether stories section or financials section should appear first on the IR20 home page.
> 
> **This should not be confused with the "Story Interest Tag" assigned to each story** (`story.interest_tag`) -- _this cookie is strictly for determining the order of content sections on the home page_.
> 
> param/cookie value	behavior
> `stories`	Stories section with story cards appears above Financials content section
> `financials`	Financials content section appears above Stories content section
> `(null)`	Content sections appear in default order, Stories above Financials
> cc: @tskillern @pspaeth

@mattroush I'm working on the Story Cards ordering now, and I realized I think there is a discrepancy here with the **interest cookie**.

The requirements doc includes this case for the Home page Story Cards module:
_"Here are some use cases for a user’s visit: ....
I click on a link in an email that is meant for student-affinity audiences. The link specifies that the stories are ordered by interest, with student stories first, then by priority."_

That would mean that there SHOULD be an interest cookie correlating with interest tags, so that story cards can be ordered by interest as well as by campus.

@tskillern Please confirm if story cards on the home page can be ordered by campus AND interest, or just campus.

**Comment by mattroush** [comment]
@kmackvolt my guess is that that requirement use case was written before this home page functionality was finalized. 

My earlier post here describes final, approved functionality. One cookie -- interest -- governs order of content sections on home page (_Story Cards module on top or Financials module on top, with stories being the default_). Another cookie -- campus -- governs story card sorting order in the Story Cards module.

For the story cards, then, the use case would be re-written as:
_I click on a link in an email that is meant for Boulder audiences. The link specifies that the stories are first ordered by campus, with Boulder stories first, then by priority._

cc: @kreynen @tskillern @pspaeth

**Comment by tskillern** [comment]
@kmackvolt @mattroush What Matt said is correct. We only need to order story cards by campus. 

Tim

cc @kreynen @pspaeth
